### ISSUE TITLE
Error When Running Make

### ISSUE THREAD

**Issue by ammohseni** [Expander/tsil-mma#1]
Hello,

I get the following error when I run "make" after "cmake -DTSIL_DIR=/path/to/tsil -DCMAKE_CXX_FLAGS=-DTSIL_SIZE_LONG .."

/tsil-mma-master/src/librarylink.cpp:242:14: error: 
      implicit conversion from 'TSIL_COMPLEX' (aka '_Complex long double') to
      'long double' is not permitted in C++
   data.Ax = TSIL_A(x, qq);

and it appears several times. My operating system is macos catalina 10.15.

Regards.

**Comment by Expander** [comment]
Hi,

many thanks for reporting this issue! Can you please tell your compiler type and version and the TSIL version you're using?

Best,
Alex

**Comment by Expander** [comment]
Just a quick update: I could reproduce the error message with clang++ 10. I will prepare a fix for you as soon as possible (hopefully within the next few days).

The compiler error does not appear when using g++ 8. This may be a temporary workaround if this issue is time critical for you.

**Comment by Expander** [comment]
I've found a quick fix. Could you please try with the latest commit a1975942 ?

**Comment by ammohseni** [comment]
Hello,

Thanks a lot, there errors do not show up now but I get a warning:

ld: warning: could not create compact unwind for _TSIL_rk6: stack subq instruction is too different from dwarf stack size

Best regards.

**Comment by ammohseni** [comment]
Continuing in spite of the mentioned warning, I get the following error in Mathematica upon running TSILInitialize[libName];         
                     
LibraryFunction::noopen: Cannot open src/LibraryLink.so.

Thank you in advance.

Best regards.

**Comment by Expander** [comment]
I've opened a new issue #2 for this. Let's continue to discuss there. :)
